### ISSUE TITLE
Unable to Run DGE2 Test - WorkflowDGE2 Class Not Found

### ISSUE THREAD

**Issue by zilov** [lconde-ucl/DGE2#1]
### Description of the bug

I am trying to run the test for DGE2 but encountering an error stating that the WorkflowDge class is not found. I attempted to include the class explicitly in the dge.nf file, but the error persists.

### Command used and terminal output

```console
nextflow run lconde-ucl/DGE2 -profile test --outdir ./test

ERROR ~ No such variable: WorkflowDge

 -- Check script 'DGE2/./workflows/dge.nf' at line: 16 or see '.nextflow.log' file for more details
```

### Relevant files

[nextflow_log.txt](https://github.com/user-attachments/files/15580281/nextflow_log.txt)

### System information

- Nextflow both 23.04.01 and 24.04.02
- HPC
- running locally
- profiles Docker/Singularity/Test
- os - Ubuntu 22.04
- DGE2 1.0

**Comment by lconde-ucl** [comment]
Hi @zilov,

Thank you for reporting this issue. There was a small typo which has now been corrected, so please feel free to try again. Please note that the test profile does not include the containers, so you will need to include a singularity or docker profile as well, for example:

`nextflow run lconde-ucl/DGE2 -profile test,singularity --outdir results`

The above works well for me with nextflow 23.04.4.

Thanks,
Lucia
<img width="250" alt="Screenshot 2024-06-05 at 12 35 14" src="https://github.com/lconde-ucl/DGE2/assets/13676946/a89e303b-f39c-4aeb-9609-e998cb0272d3">

**Comment by zilov** [comment]
Lucia, thank you for the fast reply and fix! Everything works now!

**Comment by smoudour** [comment]
I'm suddenly having the same issue, without having changed anything. 
At first, when I try running the pipeline, I get this message: 
```
Project `lconde-ucl/DGE2` is currently stuck on revision: 1.0 -- you need to explicitly specify a revision with the option `-r` in order to use it 
```
This is something new, I never specified which version to use.
If I proceed using -r 1.0, I get the error mentioned by the op. 

```
ERROR ~ No such variable: WorkflowDge

 -- Check script '/home/mebp/.nextflow/assets/lconde-ucl/DGE2/./workflows/dge.nf' at line: 16 or see '.nextflow.log' file for more details
```

The problem started when I tried using a params.yaml file looking like this (no idea if this has something to do with it):

```nextflow
inputdir: '~/sotiris/rnaseq/e-mtab-9014_results/'
metadata: 'emtab9014_metadata_1.txt'
outdir: 'emtab9014_dge2_results_2case_args_yaml'
design: 'Status'
condition: 'Status'
treatment: 'case'
control: 'ctr'
skip_gsea: true

```

**Comment by lconde-ucl** [comment]
Hi @smoudour,

You might be using the previous version of the pipeline, before the latest fix.

To resolve this, you can either delete the cached version and pull the latest code again:

`rm -rf /home/mebp/.nextflow/assets/lconde-ucl/DGE2/`
`nextflow run lconde-ucl/DGE2 -profile test,docker --outdir ./test`

Or explicitly run the updated version with the fix:

`nextflow run lconde-ucl/DGE2 -profile test,docker --outdir ./test -r 1.0-g1c8d3da`

I'll rename 1.0-g1c8d3da to v1.0 shortly to make it easier to reference in the future.

Let me know if you run into any issues!
Best,
Lucia

**Comment by smoudour** [comment]
Hi Lucia, 
Thanks for the prompt reply. What you proposed fixed it!

**Comment by lconde-ucl** [comment]
@smoudour I've change version 1.0 to point to the 1.0-g1c8d3da commit, so using `-r 1.0` will work the same.
Best
Lucia
